import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';

const $ = id => document.getElementById(id);
const DEFAULT = {selected:3,speed:2,paused:false,trails:true,labels:true,asteroids:true,kuiper:true,realistic:false,date:'2026-07-26'};
let state={...DEFAULT}; try{state={...state,...JSON.parse(localStorage.getItem('orrery-v3')||'{}')}}catch{};
const save=()=>{try{localStorage.setItem('orrery-v3',JSON.stringify(state))}catch{}};
const NASA={mercury:'https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/mercury/Mercury.jpg',venus:'https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/venus/Venus.jpg',earth:'https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/earth/Earth.jpg',mars:'https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/mars/Mars.jpg',jupiter:'https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/jupiter/Jupiter.jpg',saturn:'https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/saturn/Saturn.jpg',uranus:'https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/uranus/Uranus.jpg',neptune:'https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/neptune/Neptune.jpg'};
let data={bodies:[],satellites:[],events:[],tour:[]},planets=[],satellites=[],scene,camera,renderer,composer,controls,clock,simDays=0,baseDate=Date.parse(state.date+'T00:00:00Z'),focus=null,mode='orbit';
const meshes=new Map(),trails=[],labels=[],moons=[],belts=[],coronaLayers=[];const tmp=new THREE.Vector3(),canvas=$('space'),host=canvas?.parentElement;
function report(error){console.error('[ORRERY]',error)}
async function load(){try{const r=await fetch(new URL('./data.json',import.meta.url),{cache:'no-store'});if(!r.ok)throw Error(`data.json HTTP ${r.status}`);data=await r.json()}catch(e){report(e)}planets=(data.bodies||[]).map((p,index)=>({...p,index,phase:THREE.MathUtils.degToRad(index*137.5)}));satellites=data.satellites||[]}
const radius=p=>state.realistic?THREE.MathUtils.clamp(p.radiusKm/69911*.48,.018,.52):(p.id==='jupiter'?.34:p.id==='saturn'?.29:p.id==='uranus'||p.id==='neptune'?.22:.09);
const pos=(p,days,o)=>{const t=p.phase+days/p.period*Math.PI*2,b=p.a*Math.sqrt(1-p.e*p.e);return o.set(p.a*Math.cos(t)-p.a*p.e,0,b*Math.sin(t))};
function label(s){const c=document.createElement('canvas'),x=c.getContext('2d');x.font='600 40px ui-monospace,monospace';c.width=x.measureText(s).width+24;c.height=60;x.font='600 40px ui-monospace,monospace';x.fillStyle='#d9efeb';x.fillText(s,12,42);const q=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));q.scale.set(c.width/64*.35,.35,1);return q}
function orbit(p){const c=new THREE.EllipseCurve(-p.a*p.e,0,p.a,p.a*Math.sqrt(1-p.e*p.e),0,Math.PI*2);return new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(c.getPoints(256).map(v=>new THREE.Vector3(v.x,0,v.y))),new THREE.LineBasicMaterial({color:0x47747a,transparent:true,opacity:.26}))}
function radial(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d'),g=x.createRadialGradient(256,256,8,256,256,256);g.addColorStop(0,'#fff8c6');g.addColorStop(.25,'#ffd36f');g.addColorStop(.62,'#ef762d');g.addColorStop(1,'rgba(125,30,18,0)');x.fillStyle=g;x.fillRect(0,0,512,512);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function sunTex(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d'),g=x.createRadialGradient(256,256,8,256,256,250);g.addColorStop(0,'#fff3b0');g.addColorStop(.3,'#ffc35d');g.addColorStop(.78,'#e96b2d');g.addColorStop(1,'#7f251a');x.fillStyle=g;x.fillRect(0,0,512,512);for(let i=0;i<2600;i++){const a=Math.random()*6.283,r=Math.sqrt(Math.random())*240;x.globalAlpha=Math.random()*.2;x.fillStyle=i%4?'#9e371d':'#fff0a5';x.beginPath();x.arc(256+Math.cos(a)*r,256+Math.sin(a)*r,Math.random()*3+1,0,6.283);x.fill()}x.globalAlpha=1;const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function coronaMaterial(color,size,opacity){return new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uColor:{value:new THREE.Color(color)},uSize:{value:size},uOpacity:{value:opacity}},vertexShader:`uniform float uSize;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);gl_PointSize=uSize*(240.0/-mv.z);gl_Position=projectionMatrix*mv;}`,fragmentShader:`uniform vec3 uColor;uniform float uOpacity;void main(){vec2 p=gl_PointCoord-.5;float d=length(p);if(d>.5)discard;float a=pow(1.0-d*2.0,2.0)*uOpacity;gl_FragColor=vec4(uColor,a);}`})}
function sun(){scene.add(new THREE.Mesh(new THREE.SphereGeometry(.5,64,32),new THREE.MeshBasicMaterial({map:sunTex()})));const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:radial(),color:0xff8b35,transparent:true,opacity:.34,blending:THREE.AdditiveBlending,depthWrite:false}));glow.scale.set(2.15,2.15,1);scene.add(glow);scene.add(new THREE.PointLight(0xffc477,4.8,0,0));for(let layer=0;layer<3;layer++){const g=new THREE.BufferGeometry(),a=new Float32Array(300*3);for(let i=0;i<300;i++){const u=Math.random()*2-1,t=Math.random()*6.283,r=.58+layer*.12+Math.random()*.14,s=Math.sqrt(1-u*u);a[i*3]=r*s*Math.cos(t);a[i*3+1]=r*u;a[i*3+2]=r*s*Math.sin(t)}g.setAttribute('position',new THREE.BufferAttribute(a,3));const q=new THREE.Points(g,coronaMaterial(layer===1?0xffd27a:0xff7c32,3.4+layer*.9,.55));scene.add(q);coronaLayers.push(q)}}
function tex(p,m){const u=NASA[p.id];if(!u)return;new THREE.TextureLoader().load(u,t=>{t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();m.map=t;m.needsUpdate=true},undefined,e=>report(e))}
function rings(m){const g=new THREE.Group();g.rotation.x=Math.PI/2;g.rotation.z=THREE.MathUtils.degToRad(26.7);g.add(new THREE.Mesh(new THREE.RingGeometry(1.45,3.25,256),new THREE.MeshBasicMaterial({color:0xcbb58d,side:THREE.DoubleSide,transparent:true,opacity:.9,depthWrite:false})));g.add(new THREE.Mesh(new THREE.RingGeometry(2.05,2.28,256),new THREE.MeshBasicMaterial({color:0x0d1518,side:THREE.DoubleSide,transparent:true,opacity:.98,depthWrite:false})));g.add(new THREE.Mesh(new THREE.RingGeometry(1.58,1.7,256),new THREE.MeshBasicMaterial({color:0x806f57,side:THREE.DoubleSide,transparent:true,opacity:.78,depthWrite:false})));m.add(g)}
function belt(n,min,max,color,key){const g=new THREE.BufferGeometry(),a=new Float32Array(n*3);for(let i=0;i<n;i++){const r=min+Math.random()*(max-min),t=Math.random()*6.283;a[i*3]=r*Math.cos(t);a[i*3+1]=(Math.random()-.5)*.22*(r/min);a[i*3+2]=r*Math.sin(t)}g.setAttribute('position',new THREE.BufferAttribute(a,3));const q=new THREE.Points(g,new THREE.PointsMaterial({color,size:key==='kuiper'?.05:.032,transparent:true,opacity:.38}));q.userData.key=key;scene.add(q);belts.push(q)}
function resize(){if(!renderer||!host)return;const w=host.clientWidth,h=host.clientHeight;if(w<2||h<2)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);composer?.setSize(w,h)}
function select(i,move=true){const p=planets[i];if(!p)return;state.selected=i;$('body-name').textContent=p.name;$('body-type').textContent=p.type;$('body-fact').textContent=p.fact;$('body-composition').textContent=p.composition;$('body-temp').textContent=p.temperature;$('body-gravity').textContent=p.gravity;$('body-day').textContent=p.day;$('body-missions').textContent=p.missions;$('body-moons').textContent=p.moons.length;$('readout-body').textContent=p.name.toUpperCase();$('planet-orb').style.background=`radial-gradient(circle at 35% 30%,${p.color},#322528 70%)`;$('nearby-count').textContent=`${p.moons.length} active`;$('orbiter-list').innerHTML=p.moons.length?p.moons.map(n=>`<button class="orbiter-chip">${n}</button>`).join(''):'<span class="muted">No major satellites in model</span>';if(move){focus=meshes.get(p.id);mode='follow'}save()}
function init(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x07151a,0.006);camera=new THREE.PerspectiveCamera(45,1,.01,500);camera.position.set(0,8,15);controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=1;controls.maxDistance=100;clock=new THREE.Clock();scene.add(new THREE.AmbientLight(0x6b8d8d,.25));sun();const g=new THREE.BufferGeometry(),a=new Float32Array(9000*3);for(let i=0;i<a.length;i++)a[i]=(Math.random()-.5)*220;g.setAttribute('position',new THREE.BufferAttribute(a,3));scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:0xbdd9d7,size:.06})));planets.forEach(p=>{const pivot=new THREE.Group();pivot.rotation.x=THREE.MathUtils.degToRad(p.i);scene.add(pivot);const line=orbit(p);pivot.add(line);trails.push(line);const mtl=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.88,metalness:.01});const m=new THREE.Mesh(new THREE.SphereGeometry(1,64,32),mtl);m.scale.setScalar(radius(p));m.userData.id=p.id;pivot.add(m);meshes.set(p.id,m);tex(p,mtl);const l=label(p.name);pivot.add(l);labels.push(l);if(p.id==='saturn')rings(m)});satellites.forEach((body,index)=>{const parent=meshes.get(body.parent);if(!parent)return;const pivot=new THREE.Group();pivot.position.set(Math.max(body.a,.11),0,0);pivot.rotation.x=THREE.MathUtils.degToRad(body.inclination||3);parent.add(pivot);pivot.add(new THREE.Mesh(new THREE.SphereGeometry(Math.max(body.radius,.035),24,12),new THREE.MeshStandardMaterial({color:body.color,roughness:.92})));moons.push({pivot,body,phase:index*1.7})});belt(1800,2.1,3.2,0xa17b55,'asteroids');belt(1100,35,43,0x6c8cad,'kuiper');composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(host.clientWidth,host.clientHeight),0.72,0.8,0.82);composer.addPass(bloom);new ResizeObserver(resize).observe(host);resize();let down={x:0,y:0};canvas.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=canvas.getBoundingClientRect(),v=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(v,camera);const hit=ray.intersectObjects([...meshes.values()],false)[0];if(hit)select(planets.findIndex(p=>p.id===hit.object.userData.id))});animate()}catch(e){report(e)}}
function animate(){requestAnimationFrame(animate);try{const dt=Math.min(clock.getDelta(),.1);if(!state.paused)simDays+=dt*state.speed;planets.forEach(p=>{const m=meshes.get(p.id);pos(p,simDays,m.position);const l=labels[p.index];l.position.copy(m.position);l.position.y+=radius(p)+.2;l.visible=state.labels;trails[p.index].visible=state.trails});moons.forEach(({pivot,body,phase})=>pivot.rotation.y=phase+simDays/body.period*6.283);belts.forEach(b=>{b.visible=Boolean(state[b.userData.key]);b.rotation.y+=dt*(b.userData.key==='kuiper'?.004:.012)});coronaLayers.forEach((layer,i)=>{layer.rotation.y+=dt*(.08+i*.04);layer.rotation.x+=dt*.025;layer.material.uniforms.uOpacity.value=.42+Math.sin(performance.now()*.002+i)*.1});if(mode==='cinematic'){scene.rotation.y+=dt*.012;camera.position.x=Math.sin(performance.now()*.00009)*18;camera.position.y=6+Math.sin(performance.now()*.00013)*2;camera.position.z=18+Math.cos(performance.now()*.00009)*8;controls.target.lerp(new THREE.Vector3(0,0,0),.02)}if(focus&&mode==='follow'){focus.getWorldPosition(tmp);controls.target.lerp(tmp,.1);camera.position.lerp(tmp.clone().add(new THREE.Vector3(2,1,2)),.08)}controls.update();const date=new Date(baseDate+simDays*86400000).toISOString().slice(0,10).toUpperCase();$('sim-date').textContent=date;$('timeline-label').textContent=`${date} · 14:32 UTC`;$('deck-date').textContent=date;$('readout-zoom').textContent=`${(15/Math.max(camera.position.distanceTo(controls.target),.01)).toFixed(1)}×`;$('readout-speed').textContent=`${state.speed} d/s`;composer.render()}catch(e){report(e)}}
function catalog(){const t=$('catalog-grid');if(t)t.innerHTML=planets.map(p=>`<article class="catalog-item"><div class="catalog-item-head"><span class="catalog-dot" style="--planet:${p.color}"></span><span class="kicker">${p.type}</span></div><div><h3>${p.name}</h3><p>${p.fact}</p></div><div class="catalog-footer"><span>${Number(p.radiusKm).toLocaleString()} km · ${p.moons.length} moons</span><button class="catalog-focus" data-focus="${p.id}">FOCUS ↗</button></div></article>`).join('')}
function events(){const t=$('event-list');if(t)t.innerHTML=(data.events||[]).map(e=>`<div class="event-row"><time>${e.date}</time><div><b>${e.title}</b><p>${e.copy}</p></div><button class="event-jump" data-offset="${e.offset}">JUMP →</button></div>`).join('')}
function compare(){const a=$('compare-a'),b=$('compare-b');if(!a||!b)return;a.innerHTML=b.innerHTML=planets.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');a.value='earth';b.value='mars';const update=()=>{const x=planets.find(p=>p.id===a.value)||planets[0],y=planets.find(p=>p.id===b.value)||planets[1];if(!x||!y)return;for(const [k,p] of [['a',x],['b',y]]){$('compare-name-'+k).textContent=p.name;$('compare-radius-'+k).textContent=`${Number(p.radiusKm).toLocaleString()} km radius`;$('compare-orb-'+k).style.background=`radial-gradient(circle at 35% 30%,${p.color},#322528 70%)`}const mr=Math.max(x.radiusKm,y.radiusKm),mm=Math.max(x.massEarth,y.massEarth);$('bar-radius-a').style.width=`${x.radiusKm/mr*100}%`;$('bar-radius-b').style.width=`${y.radiusKm/mr*100}%`;$('bar-mass-a').style.width=`${x.massEarth/mm*100}%`;$('bar-mass-b').style.width=`${y.massEarth/mm*100}%`};a.onchange=b.onchange=update;update()}
function bind(){document.querySelectorAll('.rail-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===b.dataset.view));document.querySelectorAll('.rail-btn').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='system')requestAnimationFrame(resize)});document.querySelectorAll('[data-setting]').forEach(i=>{i.checked=Boolean(state[i.dataset.setting]);i.onchange=()=>{state[i.dataset.setting]=i.checked;save()}});document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{mode=b.id.replace('mode-','');if(mode==='orbit')focus=null});$('compare-btn').onclick=()=>$('compare-dialog').showModal();$('close-compare').onclick=()=>$('compare-dialog').close();$('reset-settings').onclick=()=>{localStorage.removeItem('orrery-v3');location.reload()};$('catalog-grid').onclick=e=>{const b=e.target.closest('[data-focus]');if(!b)return;select(planets.findIndex(p=>p.id===b.dataset.focus));document.querySelector('.rail-btn[data-view="system"]').click()};document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{const e=data.events.find(x=>x.title.toLowerCase().includes(b.dataset.event.split('-')[0]));if(e){simDays=Number(e.offset);$('timeline').value=e.offset}});document.querySelectorAll('.event-jump').forEach(b=>b.onclick=()=>{simDays=Number(b.dataset.offset);$('timeline').value=b.dataset.offset});$('today-btn').onclick=()=>{simDays=0;$('timeline').value=0};$('timeline').oninput=e=>simDays=Number(e.target.value);document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();state.paused=!state.paused;save()}if(e.key.toLowerCase()==='r')$('today-btn').click();if(/^[1-8]$/.test(e.key))select(Number(e.key)-1)})}
async function boot(){try{await load();catalog();events();compare();select(Math.min(Number(state.selected)||0,planets.length-1),false);bind();init()}catch(e){report(e)}}boot();