import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';

const $ = id => document.getElementById(id);
const DEFAULT = { selected: 3, speed: 2, paused: false, trails: true, labels: true, asteroids: true, kuiper: true, realistic: false, date: '2026-07-26' };
let state = { ...DEFAULT };
try { state = { ...state, ...JSON.parse(localStorage.getItem('orrery-v3') || '{}') }; } catch {}
const save = () => { try { localStorage.setItem('orrery-v3', JSON.stringify(state)); } catch {} };
const TEXTURES = Object.fromEntries(['mercury','venus','earth','mars','jupiter','saturn','uranus','neptune'].map(id => [id, `https://assets.science.nasa.gov/content/dam/science/cds/3d/resources/image/${id}/${id[0].toUpperCase()+id.slice(1)}.jpg`]));
let data = { bodies: [], satellites: [], events: [], tour: [] }, planets = [], satellites = [];
let scene, camera, renderer, composer, controls, clock, simDays = 0, baseDate = Date.parse(state.date + 'T00:00:00Z'), focus = null, mode = 'orbit';
const meshes = new Map(), pivots = new Map(), trails = [], labels = [], moons = [], movingBelts = [], tmp = new THREE.Vector3();
const canvas = $('space'), host = canvas?.parentElement;
const report = e => console.error('[ORRERY]', e);

async function loadData() {
  try { const r = await fetch(new URL('./data.json', import.meta.url), { cache: 'no-store' }); if (!r.ok) throw Error(`data.json ${r.status}`); data = await r.json(); } catch (e) { report(e); }
  planets = (data.bodies || []).map((p, i) => ({ ...p, index: i, phase: i * 2.399 }));
  satellites = data.satellites || [];
}
const radius = p => state.realistic ? THREE.MathUtils.clamp(p.radiusKm / 69911 * .48, .018, .52) : ({ jupiter: .34, saturn: .29, uranus: .22, neptune: .22 }[p.id] || .09);
const position = (p, days, out) => { const t = p.phase + days / p.period * Math.PI * 2, b = p.a * Math.sqrt(1 - p.e * p.e); return out.set(p.a * Math.cos(t) - p.a * p.e, 0, b * Math.sin(t)); };

function label(text) { const c = document.createElement('canvas'), x = c.getContext('2d'); x.font = '600 40px ui-monospace,monospace'; c.width = x.measureText(text).width + 24; c.height = 60; x.font = '600 40px ui-monospace,monospace'; x.fillStyle = '#d9efeb'; x.fillText(text, 12, 42); const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: new THREE.CanvasTexture(c), transparent: true, depthTest: false })); s.scale.set(c.width / 64 * .35, .35, 1); return s; }
function orbit(p) { const c = new THREE.EllipseCurve(-p.a * p.e, 0, p.a, p.a * Math.sqrt(1 - p.e * p.e), 0, Math.PI * 2); return new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(c.getPoints(256).map(v => new THREE.Vector3(v.x, 0, v.y))), new THREE.LineBasicMaterial({ color: 0x47747a, transparent: true, opacity: .16 })); }
function loadTexture(p, material) { const url = TEXTURES[p.id]; if (!url) return; new THREE.TextureLoader().load(url, t => { t.colorSpace = THREE.SRGBColorSpace; t.anisotropy = renderer.capabilities.getMaxAnisotropy(); material.map = t; material.needsUpdate = true; }, undefined, report); }
function sun() { const c = document.createElement('canvas'); c.width = c.height = 512; const x = c.getContext('2d'), g = x.createRadialGradient(256,256,8,256,256,250); g.addColorStop(0,'#fff4b5'); g.addColorStop(.3,'#ffc65d'); g.addColorStop(.78,'#e36a2c'); g.addColorStop(1,'#7b2419'); x.fillStyle=g; x.fillRect(0,0,512,512); const tex=new THREE.CanvasTexture(c); tex.colorSpace=THREE.SRGBColorSpace; scene.add(new THREE.Mesh(new THREE.SphereGeometry(.5,64,32),new THREE.MeshBasicMaterial({map:tex}))); scene.add(new THREE.PointLight(0xffc477,1.8,0,0)); }

function makeSaturnRings(pivot) {
  const group = new THREE.Group();
  // RingGeometry lies in XY. Rotate it into a thin XZ disk, then apply Saturn's axial tilt.
  group.rotation.set(Math.PI / 2, THREE.MathUtils.degToRad(26.7), 0);
  const count = 5200, positions = new Float32Array(count * 3), colors = new Float32Array(count * 3), sizes = new Float32Array(count);
  for (let i=0;i<count;i++) { const u=Math.random(), r=1.35+(u<.55?u*.72:u<.83?.78+(u-.55)*1.7:.98+(u-.83)*2.05), a=Math.random()*Math.PI*2, y=(Math.random()-.5)*.012; positions.set([r*Math.cos(a),y,r*Math.sin(a)],i*3); const col=new THREE.Color().setHSL(.10+Math.random()*.055,.16,.44+Math.random()*.25); colors.set([col.r,col.g,col.b],i*3); sizes[i]=.012+Math.random()*.028; }
  const geo = new THREE.BufferGeometry(); geo.setAttribute('position', new THREE.BufferAttribute(positions,3)); geo.setAttribute('color', new THREE.BufferAttribute(colors,3)); geo.setAttribute('size', new THREE.BufferAttribute(sizes,1));
  const mat = new THREE.ShaderMaterial({ transparent:true, vertexColors:true, depthWrite:false, vertexShader:'attribute float size; varying vec3 vColor; void main(){vColor=color; vec4 mv=modelViewMatrix*vec4(position,1.0); gl_PointSize=size*(210.0/-mv.z); gl_Position=projectionMatrix*mv;}', fragmentShader:'varying vec3 vColor; void main(){vec2 p=gl_PointCoord-.5; if(length(p)>.5) discard; gl_FragColor=vec4(vColor,.70);}' });
  group.add(new THREE.Points(geo,mat)); pivot.add(group);
}
function makeBelt(count,min,max,color,key) { const geo=new THREE.BufferGeometry(), a=new Float32Array(count*3), c=new Float32Array(count*3); for(let i=0;i<count;i++){const r=min+Math.random()*(max-min), t=Math.random()*Math.PI*2; a.set([r*Math.cos(t),(Math.random()-.5)*.2*(r/min),r*Math.sin(t)],i*3); const col=new THREE.Color(color); col.offsetHSL((Math.random()-.5)*.04,0,(Math.random()-.5)*.18); c.set([col.r,col.g,col.b],i*3);} geo.setAttribute('position',new THREE.BufferAttribute(a,3)); geo.setAttribute('color',new THREE.BufferAttribute(c,3)); const q=new THREE.Points(geo,new THREE.PointsMaterial({size:key==='kuiper'?.038:.026,vertexColors:true,transparent:true,opacity:.24,depthWrite:false})); q.userData.key=key; scene.add(q); movingBelts.push(q); }

function renderSelection(p) { if(!p) return; for(const [id,v] of [['body-name',p.name],['body-type',p.type],['body-fact',p.fact],['body-composition',p.composition],['body-temp',p.temperature],['body-gravity',p.gravity],['body-day',p.day],['body-missions',p.missions],['body-moons',p.moons.length],['readout-body',p.name.toUpperCase()]]) $(id).textContent=v; $('nearby-count').textContent=`${p.moons.length} active`; $('orbiter-list').innerHTML=p.moons.length?p.moons.map(n=>`<button class="orbiter-chip">${n}</button>`).join(''):'<span class="muted">No major satellites in model</span>'; }
function select(i, move=true) { const p=planets[i]; if(!p) return; state.selected=i; renderSelection(p); if(move){focus=meshes.get(p.id); mode='follow';} save(); }
function catalog(){const t=$('catalog-grid');if(t)t.innerHTML=planets.map(p=>`<article class="catalog-item"><div class="catalog-item-head"><span class="catalog-dot" style="--planet:${p.color}"></span><span class="kicker">${p.type}</span></div><div><h3>${p.name}</h3><p>${p.fact}</p></div><div class="catalog-footer"><span>${Number(p.radiusKm).toLocaleString()} km · ${p.moons.length} moons</span><button class="catalog-focus" data-focus="${p.id}">FOCUS ↗</button></div></article>`).join('');}
function events(){const t=$('event-list');if(t)t.innerHTML=(data.events||[]).map(e=>`<div class="event-row"><time>${e.date}</time><div><b>${e.title}</b><p>${e.copy}</p></div><button class="event-jump" data-offset="${e.offset}">JUMP →</button></div>`).join('');}
function compare(){const a=$('compare-a'),b=$('compare-b');if(!a||!b)return;a.innerHTML=b.innerHTML=planets.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');a.value='earth';b.value='mars';const update=()=>{const x=planets.find(p=>p.id===a.value)||planets[0],y=planets.find(p=>p.id===b.value)||planets[1];if(!x||!y)return;for(const [k,p] of [['a',x],['b',y]]){$('compare-name-'+k).textContent=p.name;$('compare-radius-'+k).textContent=`${p.radiusKm.toLocaleString()} km radius`;$('compare-orb-'+k).style.background=`radial-gradient(circle at 35% 30%,${p.color},#322528 70%)`}const r=Math.max(x.radiusKm,y.radiusKm),m=Math.max(x.massEarth,y.massEarth);$('bar-radius-a').style.width=`${x.radiusKm/r*100}%`;$('bar-radius-b').style.width=`${y.radiusKm/r*100}%`;$('bar-mass-a').style.width=`${x.massEarth/m*100}%`;$('bar-mass-b').style.width=`${y.massEarth/m*100}%`};a.onchange=b.onchange=update;update();}
function resize(){if(!renderer||!host)return;const w=host.clientWidth,h=host.clientHeight;if(w<2||h<2)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);composer?.setSize(w,h);}
function init(){ renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5)); renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=.7; scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x07151a,.0025); camera=new THREE.PerspectiveCamera(45,1,.01,500); camera.position.set(0,8,15); controls=new OrbitControls(camera,canvas); controls.enableDamping=true; controls.dampingFactor=.06; controls.minDistance=1; controls.maxDistance=100; clock=new THREE.Clock(); scene.add(new THREE.AmbientLight(0x6b8d8d,.16)); sun(); const sg=new THREE.BufferGeometry(),sp=new Float32Array(9000*3); for(let i=0;i<sp.length;i++)sp[i]=(Math.random()-.5)*220; sg.setAttribute('position',new THREE.BufferAttribute(sp,3)); scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xbdd9d7,size:.045}));
  planets.forEach(p=>{const pivot=new THREE.Group();pivot.rotation.x=THREE.MathUtils.degToRad(p.i);scene.add(pivot);const line=orbit(p);pivot.add(line);trails.push(line);const mat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.88});const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,64,32),mat);mesh.scale.setScalar(radius(p));mesh.userData.id=p.id;pivot.add(mesh);meshes.set(p.id,mesh);pivots.set(p.id,pivot);loadTexture(p,mat);const l=label(p.name);pivot.add(l);labels.push(l);if(p.id==='saturn')makeSaturnRings(pivot);});
  satellites.forEach((body,index)=>{const parent=meshes.get(body.parent);if(!parent)return;const pivot=new THREE.Group();pivot.position.set(Math.max(body.a,.11),0,0);pivot.rotation.x=THREE.MathUtils.degToRad(body.inclination||3);parent.add(pivot);pivot.add(new THREE.Mesh(new THREE.SphereGeometry(Math.max(body.radius,.035),24,12),new THREE.MeshStandardMaterial({color:body.color,roughness:.92})));moons.push({pivot,body,phase:index*1.7});});
  makeBelt(1500,2.1,3.2,0xa17b55,'asteroids'); makeBelt(850,35,43,0x7893ad,'kuiper'); composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(host.clientWidth,host.clientHeight),.16,.45,.96));new ResizeObserver(resize).observe(host);resize();let down={x:0,y:0};canvas.onpointerdown=e=>down={x:e.clientX,y:e.clientY};canvas.onpointerup=e=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=canvas.getBoundingClientRect(),v=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(v,camera);const hit=ray.intersectObjects([...meshes.values()],false)[0];if(hit)select(planets.findIndex(p=>p.id===hit.object.userData.id));}; animate(); }
function animate(){requestAnimationFrame(animate);try{const dt=Math.min(clock.getDelta(),.1);if(!state.paused)simDays+=dt*state.speed;planets.forEach(p=>{const m=meshes.get(p.id);position(p,simDays,m.position);const l=labels[p.index];l.position.copy(m.position);l.position.y+=radius(p)+.2;l.visible=state.labels;trails[p.index].visible=state.trails;});moons.forEach(({pivot,body,phase})=>pivot.rotation.y=phase+simDays/body.period*Math.PI*2);movingBelts.forEach(b=>{b.visible=Boolean(state[b.userData.key]);b.rotation.y+=dt*(b.userData.key==='kuiper'?.003:.009);});if(mode==='cinematic'){scene.rotation.y+=dt*.009;camera.position.x=Math.sin(performance.now()*.00008)*16;camera.position.y=5+Math.sin(performance.now()*.00011)*1.5;camera.position.z=17+Math.cos(performance.now()*.00008)*7;controls.target.lerp(new THREE.Vector3(0,0,0),.018);}if(focus&&mode==='follow'){focus.getWorldPosition(tmp);controls.target.lerp(tmp,.1);camera.position.lerp(tmp.clone().add(new THREE.Vector3(2,1,2)),.08);}controls.update();const date=new Date(baseDate+simDays*86400000).toISOString().slice(0,10).toUpperCase();$('sim-date').textContent=date;$('timeline-label').textContent=`${date} · 14:32 UTC`;$('deck-date').textContent=date;$('readout-zoom').textContent=`${(15/Math.max(camera.position.distanceTo(controls.target),.01)).toFixed(1)}×`;$('readout-speed').textContent=`${state.speed} d/s`;composer.render();}catch(e){report(e);}}
function bind(){document.querySelectorAll('.rail-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===b.dataset.view));document.querySelectorAll('.rail-btn').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='system')requestAnimationFrame(resize);});document.querySelectorAll('[data-setting]').forEach(i=>{i.checked=Boolean(state[i.dataset.setting]);i.onchange=()=>{state[i.dataset.setting]=i.checked;save();};});document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{mode=b.id.replace('mode-','');if(mode==='orbit')focus=null;});$('compare-btn').onclick=()=>$('compare-dialog').showModal();$('close-compare').onclick=()=>$('compare-dialog').close();$('reset-settings').onclick=()=>{localStorage.removeItem('orrery-v3');location.reload();};$('catalog-grid').onclick=e=>{const b=e.target.closest('[data-focus]');if(!b)return;select(planets.findIndex(p=>p.id===b.dataset.focus));document.querySelector('.rail-btn[data-view="system"]').click();};document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{const e=data.events.find(x=>x.title.toLowerCase().includes(b.dataset.event.split('-')[0]));if(e){simDays=Number(e.offset);$('timeline').value=e.offset;}});document.querySelectorAll('.event-jump').forEach(b=>b.onclick=()=>{simDays=Number(b.dataset.offset);$('timeline').value=b.dataset.offset;});$('today-btn').onclick=()=>{simDays=0;$('timeline').value=0;};$('timeline').oninput=e=>simDays=Number(e.target.value);document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();state.paused=!state.paused;save();}if(e.key.toLowerCase()==='r')$('today-btn').click();if(/^[1-8]$/.test(e.key))select(Number(e.key)-1);});}
async function boot(){try{await loadData();catalog();events();compare();select(Math.min(Number(state.selected)||0,planets.length-1),false);bind();init();}catch(e){report(e);}}boot();