import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const FALLBACK={bodies:[],satellites:[],events:[],tour:[]};
let DATA=FALLBACK;try{const r=await fetch('data.json');if(r.ok)DATA=await r.json()}catch{console.warn('data.json unavailable, using empty dataset')}
const $=id=>document.getElementById(id), planets=DATA.bodies.map((p,i)=>({...p,i,phase:THREE.MathUtils.degToRad(i*137.5)})), satellites=DATA.satellites;
const defaults={selected:3,speed:2,paused:false,trails:true,labels:true,asteroids:true,kuiper:true,realistic:false,date:'2026-07-26'};let state={...defaults};try{state={...state,...JSON.parse(localStorage.getItem('orrery-v3')||'{}')}}catch{};
const save=()=>{try{localStorage.setItem('orrery-v3',JSON.stringify(state))}catch{}};
let scene,camera,renderer,controls,clock,simDays=0,baseDate=Date.parse(state.date+'T00:00:00Z'),focus=null,mode='orbit',tourIndex=0;const meshById=new Map(),pivotById=new Map(),trailMeshes=[],satMeshes=[],labelMeshes=[],tmp=new THREE.Vector3();
const canvas=$('space'),host=canvas.parentElement;
const scaleFor=p=>state.realistic?THREE.MathUtils.clamp(p.radiusKm/69911*.48,.02,.52):(p.id==='jupiter'?.34:p.id==='saturn'?.29:p.id==='uranus'?.22:p.id==='neptune'?.22:.09);
const pos=(p,days,out)=>{const t=p.phase+days/p.period*Math.PI*2,b=p.a*Math.sqrt(1-p.e*p.e);return out.set(p.a*Math.cos(t)-p.a*p.e,0,b*Math.sin(t))};
function sprite(text){const c=document.createElement('canvas'),x=c.getContext('2d');x.font='600 40px ui-monospace,monospace';c.width=x.measureText(text).width+24;c.height=60;x.font='600 40px ui-monospace,monospace';x.fillStyle='#cfe9e6';x.fillText(text,12,42);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.scale.set(c.width/64*.35,.35,1);return s}
function orbitLine(p){const c=new THREE.EllipseCurve(-p.a*p.e,0,p.a,p.a*Math.sqrt(1-p.e*p.e),0,Math.PI*2);return new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(c.getPoints(256).map(v=>new THREE.Vector3(v.x,0,v.y))),new THREE.LineBasicMaterial({color:0x315d63,transparent:true,opacity:.55}))}
function init3D(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(45,1,.01,500);camera.position.set(0,8,15);controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=1;controls.maxDistance=100;clock=new THREE.Clock();scene.add(new THREE.AmbientLight(0x6b8d8d,.3),new THREE.PointLight(0xffbf7a,3,0,0),new THREE.Mesh(new THREE.SphereGeometry(.5,48,24),new THREE.MeshBasicMaterial({color:0xffb55f})));const stars=new THREE.BufferGeometry(),a=new Float32Array(8500*3);for(let i=0;i<a.length;i++)a[i]=(Math.random()-.5)*220;stars.setAttribute('position',new THREE.BufferAttribute(a,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0xbdd9d7,size:.075})));planets.forEach(p=>{const pivot=new THREE.Group();pivot.rotation.x=THREE.MathUtils.degToRad(p.i);scene.add(pivot);const line=orbitLine(p);pivot.add(line);trailMeshes.push(line);const m=new THREE.Mesh(new THREE.SphereGeometry(1,48,24),new THREE.MeshStandardMaterial({color:p.color,roughness:.78}));m.scale.setScalar(scaleFor(p));m.userData.id=p.id;pivot.add(m);meshById.set(p.id,m);pivotById.set(p.id,pivot);const l=sprite(p.name);pivot.add(l);labelMeshes.push(l);if(p.id==='saturn'){const ring=new THREE.Mesh(new THREE.RingGeometry(.42,.78,96),new THREE.MeshBasicMaterial({color:0xb8a47b,side:THREE.DoubleSide,transparent:true,opacity:.68}));ring.rotation.x=Math.PI/2+THREE.MathUtils.degToRad(26.7);m.add(ring)}});satellites.forEach((s,i)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(s.radius,16,10),new THREE.MeshStandardMaterial({color:s.color,roughness:1}));scene.add(m);satMeshes.push({mesh:m,data:s,phase:i})});buildBelts();new ResizeObserver(resize).observe(host);resize();canvas.addEventListener('pointerup',pick);animate()}catch(e){$('webgl-error').hidden=false;console.error(e)}}
function buildBelts(){const make=(count,min,max,color,key)=>{const g=new THREE.BufferGeometry(),a=new Float32Array(count*3);for(let i=0;i<count;i++){const r=min+Math.random()*(max-min),t=Math.random()*Math.PI*2;a[i*3]=r*Math.cos(t);a[i*3+1]=(Math.random()-.5)*.18;a[i*3+2]=r*Math.sin(t)}g.setAttribute('position',new THREE.BufferAttribute(a,3));const p=new THREE.Points(g,new THREE.PointsMaterial({color,size:key==='kuiper'?.07:.045,transparent:true,opacity:.55}));p.userData.key=key;scene.add(p)};make(2200,2.1,3.2,0xb08761,'asteroids');make(1400,35,43,0x708db0,'kuiper')}
function resize(){if(!renderer)return;const w=host.clientWidth,h=host.clientHeight;if(w<2||h<2)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.1);if(!state.paused)simDays+=dt*state.speed;planets.forEach(p=>{const m=meshById.get(p.id);pos(p,simDays,m.position);const label=labelMeshes[p.i];label.position.copy(m.position);label.position.y+=scaleFor(p)+.2;label.visible=state.labels;trailMeshes[p.i].visible=state.trails});satMeshes.forEach(({mesh,data,phase})=>{const parent=meshById.get(data.parent);if(!parent)return;const v=parent.getWorldPosition(tmp),t=phase+simDays/data.period*Math.PI*2;mesh.position.set(v.x+data.a*Math.cos(t),v.y,v.z+data.a*Math.sin(t))});scene.traverse(o=>{if(o.userData.key)o.visible=Boolean(state[o.userData.key])});if(mode==='cinematic')scene.rotation.y+=dt*.018;if(focus){focus.getWorldPosition(tmp);controls.target.lerp(tmp,.1);if(mode==='follow')camera.position.lerp(tmp.clone().add(new THREE.Vector3(2,1,2)),.08)}controls.update();const d=new Date(baseDate+simDays*86400000),label=d.toISOString().slice(0,10).toUpperCase();$('sim-date').textContent=label;$('timeline-label').textContent=label+' · 14:32 UTC';$('deck-date').textContent=label;$('readout-zoom').textContent=(15/Math.max(camera.position.distanceTo(controls.target),.01)).toFixed(1)+'×'}
function renderSelection(p){$('body-name').textContent=p.name;$('body-type').textContent=p.type;$('body-fact').textContent=p.fact;$('body-composition').textContent=p.composition;$('body-temp').textContent=p.temperature;$('body-gravity').textContent=p.gravity;$('body-day').textContent=p.day;$('body-missions').textContent=p.missions;$('body-moons').textContent=p.moons.length;$('readout-body').textContent=p.name.toUpperCase();$('planet-orb').style.background=`radial-gradient(circle at 35% 30%,${p.color},#322528 70%)`;$('nearby-count').textContent=p.moons.length+' active';$('orbiter-list').innerHTML=p.moons.length?p.moons.map(x=>`<button class="orbiter-chip">${x}</button>`).join(''):'<span class="muted">No major satellites in model</span>'}
function select(i,move=true){if(!planets[i])return;state.selected=i;renderSelection(planets[i]);if(move){focus=meshById.get(planets[i].id);setMode('follow')}save()}
function pick(e){const r=canvas.getBoundingClientRect(),v=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(v,camera);const hit=ray.intersectObjects([...meshById.values()],false)[0];if(hit)select(planets.findIndex(p=>p.id===hit.object.userData.id))}
function setMode(m){mode=m;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.id==='mode-'+m));if(m==='orbit')focus=null;if(m==='cinematic')focus=meshById.get(planets[(state.selected+1)%planets.length].id)}
function renderCatalog(){$('catalog-grid').innerHTML=planets.map(p=>`<article class="catalog-item"><div class="catalog-item-head"><span class="catalog-dot" style="--planet:${p.color}"></span><span class="kicker">${p.type}</span></div><div><h3>${p.name}</h3><p>${p.fact}</p></div><div class="catalog-footer"><span>${p.radiusKm.toLocaleString()} km · ${p.moons.length} moons</span><button class="catalog-focus" data-focus="${p.id}">FOCUS ↗</button></div></article>`).join('')}
function renderEvents(){$('event-list').innerHTML=DATA.events.map(e=>`<div class="event-row"><time>${e.date}</time><div><b>${e.title}</b><p>${e.copy}</p></div><button class="event-jump" data-offset="${e.offset}">JUMP →</button></div>`).join('')}
function renderCompare(){const a=$('compare-a'),b=$('compare-b');a.innerHTML=b.innerHTML=planets.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');a.value='earth';b.value='mars';const update=()=>{const x=planets.find(p=>p.id===a.value),y=planets.find(p=>p.id===b.value);[['a',x],['b',y]].forEach(([k,p])=>{$('compare-name-'+k).textContent=p.name;$('compare-radius-'+k).textContent=p.radiusKm.toLocaleString()+' km radius';$('compare-orb-'+k).style.background=`radial-gradient(circle at 35% 30%,${p.color},#322528 70%)`});const mr=Math.max(x.radiusKm,y.radiusKm),mm=Math.max(x.massEarth,y.massEarth);$('bar-radius-a').style.width=x.radiusKm/mr*100+'%';$('bar-radius-b').style.width=y.radiusKm/mr*100+'%';$('bar-mass-a').style.width=x.massEarth/mm*100+'%';$('bar-mass-b').style.width=y.massEarth/mm*100+'%'};a.onchange=b.onchange=update;update()}
function tour(show=true){$('tour-overlay').hidden=!show;if(show){const t=DATA.tour[tourIndex];if(!t)return;$('tour-step').textContent=String(tourIndex+1).padStart(2,'0');$('tour-title').textContent=t.title;$('tour-description').textContent=t.copy;if(meshById.has(t.body)){focus=meshById.get(t.body);setMode('follow')}}}
function bind(){document.querySelectorAll('.rail-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===b.dataset.view));document.querySelectorAll('.rail-btn').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-setting]').forEach(x=>{x.checked=Boolean(state[x.dataset.setting]);x.onchange=()=>{state[x.dataset.setting]=x.checked;save()}});document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setMode(b.id.replace('mode-','')));$('compare-btn').onclick=()=>$('compare-dialog').showModal();$('close-compare').onclick=()=>$('compare-dialog').close();$('tour-btn').onclick=()=>tour();$('observe-tour').onclick=()=>tour();$('tour-close').onclick=()=>tour(false);$('tour-skip').onclick=()=>tour(false);$('tour-next').onclick=()=>{tourIndex=(tourIndex+1)%DATA.tour.length;tour()};$('clear-selection').onclick=()=>{focus=null;setMode('orbit')};$('reset-settings').onclick=()=>{localStorage.removeItem('orrery-v3');location.reload()};$('catalog-grid').onclick=e=>{const b=e.target.closest('[data-focus]');if(!b)return;select(planets.findIndex(p=>p.id===b.dataset.focus));document.querySelector('.rail-btn[data-view="system"]').click()};document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{$('timeline').value=DATA.events.find(e=>e.title.toLowerCase().includes(b.dataset.event.split('-')[0]))?.offset||0});document.querySelectorAll('.event-jump').forEach(b=>b.onclick=()=>{$('timeline').value=b.dataset.offset;simDays=Number(b.dataset.offset)});$('today-btn').onclick=()=>{$('timeline').value=0;simDays=0};$('timeline').oninput=e=>simDays=Number(e.target.value);document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();state.paused=!state.paused;save()}if(e.key.toLowerCase()==='r'){$('today-btn').click()}if(/^[1-8]$/.test(e.key))select(Number(e.key)-1)})}
renderCatalog();renderEvents();renderCompare();select(Math.min(state.selected,planets.length-1),false);bind();init3D();
